### PR TITLE
Consolidate configuration services

### PR DESCRIPTION
**Pull request by io7m**
**What's this do?**
This moves the existing catalog/settings configuration services
into one buildconfig service. This allows for removing the dependency
between the ui-settings and ui-catalog modules. Additionally, I ran the
"find unnecessary module dependencies" IDEA inspection and found (and
removed) a few unnecessary dependencies (mostly simplified-json-core).

**Why are we doing this? (w/ JIRA link if applicable)**
Minor technical debt cleanup.

**How should this be tested? / Do these changes have associated tests?**
N/A

**Dependencies for merging? Releasing to production?**
None.

**Has the application documentation been updated for these changes?**
N/A

**Did someone actually run this code to verify it works?**
@io7m ran the vanilla app

### CODE REVIEW

**Comment by twaddington** [comment]
> Additionally, I ran the "find unnecessary module dependencies" IDEA inspection and found (and removed) a few unnecessary dependencies (mostly simplified-json-core). &mdash; @io7m 

Nice 🎉

**Comment by io7m** [comment]
Forgot to remove the actual dependency though. :roll_eyes: 

One minute...

**Comment by twaddington** [comment]
@io7m I don't see the `simplified-json-core` removals?

**Comment by io7m** [comment]
You're right... I asked IDEA to remove the module dependencies, but it seems like it removed the dependencies from its internal model but didn't actually modify the `build.gradle` files.

**Comment by io7m** [comment]
Turns out the IDEA inspection gives false positives due to transitive dependencies.

**Pull request merged**
