### PR TITLE
Removed simplified-app-vanilla-with-profiles and added new flavor to simplified-app-vanilla.

### PR DESCRIPTION
**Pull request by twaddington**
**What's this do?**
This change removes the `simplified-app-vanilla-with-profiles` module and adds a new build flavor to `simplified-app-vanilla` named `vanillaWithProfiles` .

**Why are we doing this? (w/ JIRA link if applicable)**
The "with-profiles" app was largely duplicative of the base "vanilla" sample app. Merging the two together eliminated some redundant code and will make them easier to maintain in the future. For example, it will no longer be necessary to update both projects when a new activity is added (e.g. card-creator).

**How should this be tested? / Do these changes have associated tests?**
The two flavors should be built and run to verify they work as before.

```
./gradlew clean
./gradlew :simplified-app-vanilla:assemble
./gradlew :simplified-app-vanilla:installVanillaDebug
./gradlew :simplified-app-vanilla:installVanillaWithProfilesDebug
```

**Dependencies for merging? Releasing to production?**
n/a

**Has the application documentation been updated for these changes?**
Yes.

**Did someone actually run this code to verify it works?**
@twaddington

### CODE REVIEW

**Comment by io7m** [comment]
This seems OK. My only issue with this is that the output APK files have odd names:

```
./simplified-app-vanilla/build/outputs/apk/vanillaWithProfiles/debug/5.0.0-7007-vanillaWithProfiles-debug.apk
./simplified-app-vanilla/build/outputs/apk/vanilla/debug/5.0.0-7007-vanilla-debug.apk
```

Doesn't really fit with the names as they've appeared in the `android-binaries` repos to date.

**Comment by twaddington** [comment]
> Doesn't really fit with the names as they've appeared in the `android-binaries` repos to date. &mdash; @io7m 

Yeah, I noticed that 😕I can fix the archive names but it requires a little bit of extra code. Are we relying on those names to be consistent or is it more of an aesthetic concern?

**Comment by io7m** [comment]
It might upset pushing to Central. I'm not sure yet... I'm hoping the publication plugin(s) do the necessary mangling to get artifact names into a sensible format.

We don't depend on pushing those APKs to Central in any way, but the current publication process seems to be all-or-nothing, so it does need to keep working.

**Comment by twaddington** [comment]
> We don't depend on pushing those APKs to Central in any way, but the current publication process seems to be all-or-nothing, so it does need to keep working. &mdash; @io7m 

Got it! That makes sense. Would it make sense to skip publishing APKs and just do Jars and AARs? Or do we want those APKs archived?

**Comment by io7m** [comment]
> Got it! That makes sense. Would it make sense to skip publishing APKs and just do Jars and AARs? Or do we want those APKs archived in central?

I'm not sure. It's nice to have, but we don't depend on it.

**Comment by twaddington** [comment]
> It's nice to have, but we don't depend on it. &mdash; @io7m 

Hrm, well I added a commit that disables publishing for `android-application` projects. It's easy to revert if we decide we'd rather keep those archives.

I also extracted the publishing configuration block from `build.gradle` and moved it to `publishing.gradle` to clean that file up a bit.

**Comment by io7m** [comment]
I think we should go for it. :tada:

**Pull request merged**
