### PR TITLE
Fix a few possible crashes on app startup as seen in Firebase

### PR DESCRIPTION
**Pull request by twaddington**
**Why are we doing this? (w/ JIRA link if applicable)**
- https://console.firebase.google.com/project/simplye-nypl/crashlytics/app/android:org.nypl.simplified.simplye/issues/01496df5f6758b6ba270f6ed3f8fc46f
- https://console.firebase.google.com/project/simplye-nypl/crashlytics/app/android:org.nypl.simplified.simplye/issues/43fb299ddf1974a4221a4c69500daeb5
- https://console.firebase.google.com/project/simplye-nypl/crashlytics/app/android:org.nypl.simplified.simplye/issues/f2095f5c847a085b901dcfb64945a4dc

**How should this be tested? / Do these changes have associated tests?**
Run the app and make sure it starts up successfully.

**Dependencies for merging? Releasing to production?**
n/a

**Has the application documentation been updated for these changes?**
n/a

**Did someone actually run this code to verify it works?**
@twaddington ran the vanilla app.

### CODE REVIEW

**Comment by io7m** [comment]
I don't object to these changes in general, but looking at some of them, I'm wondering if we're papering over a more fundamental issue.

The splash screen code is on life support until the onboarding work, so I don't care too much about what happens to that. But is there something fundamentally wrong with the way I'm using fragments? I know fragments cause lifecycle issues, but our usage of them seems pretty straightforward and idiomatic... Are they really this broken by design?

**Comment by twaddington** [comment]
> I don't object to these changes in general, but looking at some of them, I'm wondering if we're papering over a more fundamental issue.

Yeah, these are definitely bandaid fixes for a more fundamental problem.

> But is there something fundamentally wrong with the way I'm using fragments? I know fragments cause lifecycle issues, but our usage of them seems pretty straightforward and idiomatic... Are they really this broken by design?

So, the way we're using fragments isn't wrong, it's just several years out of date and reflects the age of the app. The issues we're seeing are very common lifecycle issues that crop up when using a fragment based application. They bite new constantly and were a constant source of issues for developers maybe 3-4 years ago.

Android's Architecture components were [released in 2017](https://android-developers.googleblog.com/2017/11/announcing-architecture-components-10.html) specifically to address these kinds of issues. This isn't the only way to solve the problem of course, but it's the "officially blessed" way to do so from the Android core team.

What I think our goal should be in the short to medium term is migrate all the callback based code out of our view layer (Fragments) up into view models. Then, our fragments can subscribe to `LiveData` observers published by the view model. These are lifecycle aware and that will fix a lot of these issues.

We don't have to do away with our use of Futures or or anything. Just move that up out of any code that deals with the Android lifecycle.

**Comment by io7m** [comment]
I think it's more accurate to say it reflects my out-of-date knowledge. This UI code is only six months old... :sweat:

**Comment by twaddington** [comment]
> I think it's more accurate to say it reflects my out-of-date knowledge. This UI code is only six months old... 😓

Once things settle down I'll take a stab at refactoring one or two of the fragments to use LiveData observers and you can see what you think of the pattern.

**Pull request merged**
