### PR TITLE
Feat/sma 211 - Update CI to use App Bundles Instead of APKs

### PR DESCRIPTION
**Pull request by Dumblydore**
**What's this do?**
- Adds `firebase-bundle.conf` to SimplyE & OpenEBooks app modules which point to app bundle (.aab) (see https://github.com/NYPL-Simplified/Simplified-Android-CI/pull/1 for changes to CI script)

**Why are we doing this? (w/ JIRA link if applicable)**
https://jira.nypl.org/browse/SMA-211

**How should this be tested? / Do these changes have associated tests?**
Verify that CI build is successful and that firebase receives an .aab file instead of an .apk

**Dependencies for merging? Releasing to production?**
Requires this PR: https://github.com/NYPL-Simplified/Simplified-Android-CI/pull/1 to be merged as well

**Has the application documentation been updated for these changes?**
Yes

**Did someone actually run this code to verify it works?**
No, can only really be tested once it's merged in unfortunately

### CODE REVIEW

**Comment by io7m** [comment]
I forgot to mention: I made some progress on this a few days ago, and the process to get the build system to produce _both_ APK and AAB files is trivial. I think what we might end up doing is applying some of the changes you've made here, but without removing the publications of APK files. I've tried it out and AAB files don't make the build take any longer than normal, so I'm guessing the tools are already producing them internally anyway and they just produce APK files at the last minute from the AABs.

**Comment by MalcolmMcFly** [comment]
> I forgot to mention: I made some progress on this a few days ago, and the process to get the build system to produce _both_ APK and AAB files is trivial. I think what we might end up doing is applying some of the changes you've made here, but without removing the publications of APK files. I've tried it out and AAB files don't make the build take any longer than normal, so I'm guessing the tools are already producing them internally anyway and they just produce APK files at the last minute from the AABs.

So @io7m do you think we still want to use this?

**Comment by io7m** [comment]
We will want to use part of it! It can stay here for now.

**Comment by MalcolmMcFly** [comment]
@io7m should we close this?

**Comment by io7m** [comment]
This can be closed now.

**Pull request closed without merging**
