### PR TITLE
Bump target and compileSdkVersion to 29.

### PR DESCRIPTION
**Pull request by twaddington**
Fix some compiler errors that resulted from updating to 29. These errors
likely resulted from the addition of new nullability annotations in the
Android binaries.

### CODE REVIEW

**Comment by io7m** [comment]
Everyone's favourite Android CI issue: Accepting the stupid license agreements!

**Comment by twaddington** [comment]
Okay, I think that should do it. Assuming tests pass I will squash merge this into develop.

**Comment by io7m** [comment]
:tada:

**Review by io7m — APPROVED** [review]
Looks good!

**Pull request merged**
